owner: Waveful
repo: status.Waveful.github.io

sites:
  - name: "Website (waveful.app)"
    url: https://waveful.app
  - name: "Content Delivery Network (cdn.waveful.app)"
    url: $CDN_STATUS_URL

status-website:
  cname: status.waveful.app
  theme: ocean
  themeUrl: https://github.com/Waveful/status.Waveful.github.io/raw/master/assets/custom-theme.css  # https://upptime.js.org/docs/configuration#theme
  favicon: https://github.com/Waveful/status.Waveful.github.io/raw/master/assets/favicon.ico
  logoUrl: https://github.com/Waveful/status.Waveful.github.io/raw/master/assets/icon_512.png
  name: Waveful
  introTitle: "**Waveful** Status Dashboard"
  introMessage: "This page provides status information on the services that are part of **Waveful**. Check back here to view the current status of the services listed below. If you are experiencing an issue not listed here, please [contact Support](mailto:support@waveful.app)."
  #navbar:
  #  - title: Home
  #    href: https://waveful.app
  #  - title: Privacy
  #    href: https://waveful.app/privacy

commitMessages:
  commitAuthorName: "Dolful"
  commitAuthorEmail: "github-bot@waveful.app"

i18n:
  footer: This page is [open source](https://github.com/Waveful/status.Waveful.github.io)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
