owner: Waveful # Your GitHub organization or username, where this repository lives
repo: status.Waveful.github.io # The name of this repository

sites:
  - name: "Website (waveful.app)"
    url: https://waveful.app
  - name: "Content Delivery Network (cdn.waveful.app)"
    url: $CDN_STATUS_URL

status-website:
  cname: status.waveful.app
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Waveful
  introTitle: "**Waveful** Status Dashboard"
  introMessage: "This page provides status information on the services that are part of **Waveful**. Check back here to view the current status of the services listed below. If you are experiencing an issue not listed here, please [contact Support](mailto:support@waveful.app)."
  #navbar:
  #  - title: Home
  #    href: https://waveful.app
  #  - title: Privacy
  #    href: https://waveful.app/privacy

commitMessages:
  commitAuthorName: "Dolful"
  commitAuthorEmail: "github-bot@waveful.app"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
