owner: Waveful
repo: status.Waveful.github.io

sites:
  - name: "Website (waveful.app)"
    url: https://waveful.app
  - name: "Content Delivery Network (cdn.waveful.app)"
    url: $CDN_STATUS_URL

status-website:
  cname: status.waveful.app
  favicon: https://status.waveful.app/assets/favicon.ico
  logoUrl: https://status.waveful.app/assets/icon_512.png
  name: Waveful
  introTitle: "**Waveful** Status Dashboard"
  introMessage: " "
  links:
    - rel: stylesheet
      href: https://status.waveful.app/assets/custom-theme.css
  #navbar:
  #  - title: Home
  #    href: https://waveful.app
  #  - title: Privacy
  #    href: https://waveful.app/privacy

commitMessages:
  commitAuthorName: "Dolful"
  commitAuthorEmail: "github-bot@waveful.app"

i18n:
  footer: "If you are experiencing an issue not listed here, please [contact support](mailto:support@waveful.app)."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
